api: none
api-version: "1.15"
name: Domination
version: "1.0"
author: PoC4
main: me.lataverne.domination.Main
commands:
  domination:
    aliases: ["dom", "d"]
    description: Commande de base du plugin Domination
    permission: domination.commands
  items:
    description: Commande pour obtenir un item du plugin Domination
    permission: domination.items
